SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- [dbo].[CheckQuery] 'query2019061201'
CREATE FUNCTION [dbo].[CheckQuery]
(
	@ID		VARCHAR(50)
)
RETURNS VARCHAR(50)
AS
BEGIN
	DECLARE @QueryId VARCHAR(50)
	SET @QueryId = (SELECT DISTINCT ID FROM TemplateThemeItem WITH (NOLOCK) WHERE ID = @ID)
	RETURN @QueryId
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
