SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
-- SELECT [dbo].[ConvertHourMin](12.333)
CREATE FUNCTION [dbo].[ConvertHourMin]
(
	@segundos				NUMERIC(12, 3)
)
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @HraMin VARCHAR(8)
	SELECT @HraMin =	REPLICATE('0', 2-LEN(CAST(CAST(@segundos AS INT) / 3600 AS VARCHAR(2)))) + CAST(CAST(@segundos AS INT) / 3600 AS VARCHAR(2)) + ':'  
				+ REPLICATE('0', 2-LEN(CAST((CAST(@segundos AS INT) % 3600) / 60 AS VARCHAR(2)))) + CAST((CAST(@segundos AS INT) % 3600) / 60 AS VARCHAR(2)) + ':' 
				+ REPLICATE('0', 2-LEN(CAST((CAST(@segundos AS INT) % 60)  AS VARCHAR(2)))) + CAST((CAST(@segundos AS INT) % 60) AS VARCHAR(2))

	RETURN (@HraMin)
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
