SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE FUNCTION [dbo].[IsEmpty](@Value Varchar(255), @VaueIfEmpty Varchar(255))
RETURNS Varchar(255)
AS
BEGIN
	IF ISNULL(@Value, '') = ''
		SET  @Value = @VaueIfEmpty

	RETURN (@Value)
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
