SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
CREATE PROCEDURE [dbo].[GetAccountVcc]
(
	@InstallationId						VARCHAR(100),
	@VCC								VARCHAR(50)
)
AS
BEGIN
	SET NOCOUNT ON

	-- HACEMOS LAS BUSQUEDA DEL VCC POR EL INSTALLATIONID Y NOMBRE DEL VCC
	SELECT AV.[InstallationId] 'installationId',
			AV.[VCC] 'vcc'
		FROM dbo.[AccountVCC] AV 
		WHERE AV.[InstallationId] = @InstallationId
			AND AV.[VCC] = @VCC

	SET NOCOUNT OFF
END
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO

GO
